import tensorflow as tf
from tensorflow.keras import Model

# Discriminator
class myDiscriminator(Model):
    """
    A discriminator class for the GAIN model.

    Args:
        Dim: Dimension of data point.
        body: A kera Model that return a matrix of the same shape as data input. 
    """
    def __init__(self,body=False):
        super(myDiscriminator, self).__init__()
        if(body):
            self.body = body
    def call(self,x_hat,hints):
        """
        Discriminator model call for GAIN which is a residual block with a dense sequential body.

        Args: 
            x_hat: Data generated by generator.
            hints: hints matrix for the discriminator. 1 = genuine, 0 = generated, 0.5 = unknown

        Returns:
            Output of the generated by the generator.
        """
        return self.body(tf.concat(axis = 1, values = [x_hat,hints]))